package pvt.hrk.fileutilities.difffinder.ui.service;

import java.io.File;

import javafx.concurrent.Task;
import pvt.hrk.fileutilities.difffinder.api.FindDifference;
import pvt.hrk.fileutilities.difffinder.api.handlers.CSVStreamResultHandler;
import pvt.hrk.fileutilities.difffinder.api.other.MyFileFilterBuilder;
import pvt.hrk.fileutilities.difffinder.ui.localization.DisplayKeySupplier;

public class BackgroundTask extends Task<Void> {
	File firstDirectory;
	File secondDirectory;
	File outputFileOrDirectory;

	public BackgroundTask(File firstDirectory, File secondDirectory, File outputFileOrDirectory) {
		super();
		this.firstDirectory = firstDirectory;
		this.secondDirectory = secondDirectory;
		this.outputFileOrDirectory = outputFileOrDirectory;
	}

	@Override
	protected Void call() throws Exception {
		CSVStreamResultHandler handler = new CSVStreamResultHandler(outputFileOrDirectory);
		FindDifference.findDifference(firstDirectory, secondDirectory, MyFileFilterBuilder.EXCLUDE_AUTOGENERATED_FILES,
				handler);
		updateMessage(DisplayKeySupplier.INSTANCE.valueFor("SAVED_FILE", new Object[] {handler.getOutputFileName()}));
		return null;
	}

}
