package pvt.hrk.fileutilities.difffinder.api.main;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

import pvt.hrk.fileutilities.difffinder.api.FindDifference;
import pvt.hrk.fileutilities.difffinder.api.handlers.CSVResultHandler;
import pvt.hrk.fileutilities.difffinder.api.other.MyFileFilterBuilder;

public class CmdMain {
	 private static final Logger LOGGER = Logger.getLogger(CmdMain.class
	            .getClass().getName());
	public static void main(String[] args) {
		if (args != null && args.length >= 3) {
			String sourceDir = args[0];
			String targetDir = args[1];
			String resultFile = args[2];

			if(LOGGER.isLoggable(Level.INFO)) {
				LOGGER.info("=== Inputs received ===");
				LOGGER.info("SourceDirectory="+sourceDir);
				LOGGER.info("TargetDirectory="+targetDir);
				LOGGER.info("ResultsFile="+resultFile);
			}
			try {
				FindDifference.findDifference(new  File(sourceDir), new  File(targetDir), MyFileFilterBuilder.EXCLUDE_AUTOGENERATED_FILES,new CSVResultHandler(new File(resultFile)));
			} catch (FileNotFoundException e) {
				LOGGER.log(Level.SEVERE, e.getLocalizedMessage(),e);
			}
		} else {
			LOGGER.severe("=== Usage===");
			LOGGER.severe("CmdMain SourceDirectory TargetDirectory ResultFile");
		}
		if(LOGGER.isLoggable(Level.INFO)) {
			LOGGER.info("Finish");
		}
		
	}
}
